# Generated by Django 4.2.1 on 2023-05-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameName', models.TextField()),
                ('updateTime', models.DateTimeField(auto_now=True)),
                ('twich_views', models.IntegerField()),
                ('playtime', models.IntegerField()),
            ],
        ),
    ]
