# Generated by Django 4.2.1 on 2023-05-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerel_back', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='gameName',
        ),
        migrations.RemoveField(
            model_name='game',
            name='twich_views',
        ),
        migrations.RemoveField(
            model_name='game',
            name='updateTime',
        ),
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='real_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='twitch_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='update_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='playtime',
            field=models.IntegerField(null=True),
        ),
    ]
