# Generated by Django 4.1.7 on 2023-05-11 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamerel_back', '0002_remove_game_gamename_remove_game_twich_views_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='name',
            new_name='slug',
        ),
    ]
